[http]
  [http.routers]
    [http.routers.monit]
      entryPoints = ["https"]
      middlewares = ["monit-auth"]
      service = "monit"
      rule = "Host(`${TRAEFIK_MONIT_DOMAIN}`)"
      priority = 100

[http.middlewares]
  [http.middlewares.monit-auth.basicAuth]
    users = ["${TRAEFIK_MONIT_AUTH}"]

[http.services]
  [http.services.monit.loadBalancer]
    [[http.services.monit.loadBalancer.servers]]
      url = "http://127.0.0.1:2812"