[http]
  [http.routers]
    [http.routers.grafana]
      entryPoints = ["https"]
      service = "grafana"
      rule = "Host(`${TRAEFIK_GRAFANA_DOMAIN}`)"
      priority = 100

[http.services]
  [http.services.grafana.loadBalancer]
    [[http.services.grafana.loadBalancer.servers]]
      url = "http://127.0.0.1:3000"